package Vista;

import javax.swing.JButton;
import javax.swing.JList;
import javax.swing.JMenu;
import javax.swing.JMenuItem;

/**
 * @(#)GUI.java
 *
 *
 * @author Antonio Rivero Cuesta
 * @version 1.00 2017/4/25
 */
public class Vista extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public Vista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAgregarAlumno = new javax.swing.JButton();
        btnListarAlumno = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListAlumnos = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListProfesores = new javax.swing.JList<>();
        btnAgregarProfesor = new javax.swing.JButton();
        btnListarProfesor = new javax.swing.JButton();
        barraMenu = new javax.swing.JMenuBar();
        jMenuAlumnos = new javax.swing.JMenu();
        listaAlumnos = new javax.swing.JMenuItem();
        listaAlumnosMañana = new javax.swing.JMenuItem();
        listaAlumnosTarde = new javax.swing.JMenuItem();
        jMenuProfesores = new javax.swing.JMenu();
        listaProfesores = new javax.swing.JMenuItem();
        listaProfesoresMañana = new javax.swing.JMenuItem();
        listaProfesoresTarde = new javax.swing.JMenuItem();
        jMenuSalir = new javax.swing.JMenu();
        jMenuItemSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestion de Alumnos y Profesores");

        btnAgregarAlumno.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAgregarAlumno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Guardar 32.png"))); // NOI18N
        btnAgregarAlumno.setText("Agregar Alumno");

        btnListarAlumno.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnListarAlumno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Listar 32.png"))); // NOI18N
        btnListarAlumno.setText("Listar");

        jScrollPane2.setViewportView(jListAlumnos);

        jScrollPane3.setViewportView(jListProfesores);

        btnAgregarProfesor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAgregarProfesor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Guardar 32.png"))); // NOI18N
        btnAgregarProfesor.setText("Agregar Profesor");

        btnListarProfesor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnListarProfesor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Listar 32.png"))); // NOI18N
        btnListarProfesor.setText("Listar");

        jMenuAlumnos.setText("Menú Alumnos");

        listaAlumnos.setText("Listar todos los Alumnos");
        jMenuAlumnos.add(listaAlumnos);

        listaAlumnosMañana.setText("Ver Alumnos de la mañana");
        jMenuAlumnos.add(listaAlumnosMañana);

        listaAlumnosTarde.setText("Ver Alumno de la tarde");
        jMenuAlumnos.add(listaAlumnosTarde);

        barraMenu.add(jMenuAlumnos);

        jMenuProfesores.setText("Menú Profesores");

        listaProfesores.setText("Listar todos los Profesores");
        jMenuProfesores.add(listaProfesores);

        listaProfesoresMañana.setText("Ver Profesores de la Mañana");
        jMenuProfesores.add(listaProfesoresMañana);

        listaProfesoresTarde.setText("Ver Profesores de la tarde");
        jMenuProfesores.add(listaProfesoresTarde);

        barraMenu.add(jMenuProfesores);

        jMenuSalir.setText("Salir");

        jMenuItemSalir.setText("Salir");
        jMenuSalir.add(jMenuItemSalir);

        barraMenu.add(jMenuSalir);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 576, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 576, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAgregarProfesor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnListarProfesor))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAgregarAlumno)
                                .addGap(18, 18, 18)
                                .addComponent(btnListarAlumno)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarAlumno)
                    .addComponent(btnListarAlumno))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarProfesor)
                    .addComponent(btnListarProfesor))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // GETTERS
    public JButton getBtnAgregarAlumno() {
        return btnAgregarAlumno;
    }

    public JButton getBtnListarAlumno() {
        return btnListarAlumno;
    }

    public JList<String> getjListAlumnos() {
        return jListAlumnos;
    }

    public JButton getBtnAgregarProfesor() {
        return btnAgregarProfesor;
    }

    public JButton getBtnListarProfesor() {
        return btnListarProfesor;
    }

    public JList<String> getjListProfesores() {
        return jListProfesores;
    }

    public JMenuItem getListaAlumnos() {
        return listaAlumnos;
    }

    public JMenuItem getListaAlumnosMañana() {
        return listaAlumnosMañana;
    }

    public JMenuItem getListaAlumnosTarde() {
        return listaAlumnosTarde;
    }

    public JMenuItem getListaProfesores() {
        return listaProfesores;
    }

    public JMenuItem getListaProfesoresMañana() {
        return listaProfesoresMañana;
    }

    public JMenuItem getListaProfesoresTarde() {
        return listaProfesoresTarde;
    }

    public JMenuItem getjMenuItemSalir() {
        return jMenuItemSalir;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JButton btnAgregarAlumno;
    private javax.swing.JButton btnAgregarProfesor;
    private javax.swing.JButton btnListarAlumno;
    private javax.swing.JButton btnListarProfesor;
    private javax.swing.JList<String> jListAlumnos;
    private javax.swing.JList<String> jListProfesores;
    private javax.swing.JMenu jMenuAlumnos;
    private javax.swing.JMenuItem jMenuItemSalir;
    private javax.swing.JMenu jMenuProfesores;
    private javax.swing.JMenu jMenuSalir;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JMenuItem listaAlumnos;
    private javax.swing.JMenuItem listaAlumnosMañana;
    private javax.swing.JMenuItem listaAlumnosTarde;
    private javax.swing.JMenuItem listaProfesores;
    private javax.swing.JMenuItem listaProfesoresMañana;
    private javax.swing.JMenuItem listaProfesoresTarde;
    // End of variables declaration//GEN-END:variables
}
