/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.JButton;

/**
 *
 * @author Toni
 */
public class JDialogCurso1 extends javax.swing.JDialog {

 
            
    public JDialogCurso1(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnAsignatura1 = new javax.swing.JButton();
        btnAsignatura2 = new javax.swing.JButton();
        btnAsignatura3 = new javax.swing.JButton();
        btnAsignatura4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 51));
        jLabel1.setText("Primer Curso");

        btnAsignatura1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnAsignatura1.setForeground(new java.awt.Color(153, 0, 51));
        btnAsignatura1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Libro1-64.png"))); // NOI18N
        btnAsignatura1.setText("Asignatura 1");

        btnAsignatura2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnAsignatura2.setForeground(new java.awt.Color(153, 0, 51));
        btnAsignatura2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Libro1-64.png"))); // NOI18N
        btnAsignatura2.setText("Asignatura 2");

        btnAsignatura3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnAsignatura3.setForeground(new java.awt.Color(153, 0, 51));
        btnAsignatura3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Libro1-64.png"))); // NOI18N
        btnAsignatura3.setText("Asignatura 3");

        btnAsignatura4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnAsignatura4.setForeground(new java.awt.Color(153, 0, 51));
        btnAsignatura4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Libro1-64.png"))); // NOI18N
        btnAsignatura4.setText("Asignatura 4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAsignatura3)
                        .addGap(26, 26, 26)
                        .addComponent(btnAsignatura4))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(21, 21, 21)
                            .addComponent(btnAsignatura1)
                            .addGap(26, 26, 26)
                            .addComponent(btnAsignatura2))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(162, 162, 162)
                            .addComponent(jLabel1))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAsignatura1)
                    .addComponent(btnAsignatura2))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAsignatura3)
                    .addComponent(btnAsignatura4))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JButton getBtnAsignatura1() {
        return btnAsignatura1;
    }

    public JButton getBtnAsignatura2() {
        return btnAsignatura2;
    }

    public JButton getBtnAsignatura3() {
        return btnAsignatura3;
    }

    public JButton getBtnAsignatura4() {
        return btnAsignatura4;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAsignatura1;
    private javax.swing.JButton btnAsignatura2;
    private javax.swing.JButton btnAsignatura3;
    private javax.swing.JButton btnAsignatura4;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
