package Vista;

import javax.swing.JButton;

/**
 *
 * @author Toni
 */
public class VistaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VistaPrincipal
     */
    public VistaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        btnCurso1 = new javax.swing.JButton();
        btnCurso2 = new javax.swing.JButton();
        btnCurso3 = new javax.swing.JButton();
        btnCurso4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ventana Principal");
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 51));
        jLabel1.setText("Vista Principal");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(46, 48, 0, 45);
        getContentPane().add(jLabel1, gridBagConstraints);

        btnCurso1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnCurso1.setForeground(new java.awt.Color(153, 0, 51));
        btnCurso1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Libro1-64.png"))); // NOI18N
        btnCurso1.setText("Curso 1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(39, 80, 0, 0);
        getContentPane().add(btnCurso1, gridBagConstraints);

        btnCurso2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnCurso2.setForeground(new java.awt.Color(153, 0, 51));
        btnCurso2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Libro2-64.png"))); // NOI18N
        btnCurso2.setText("Curso 2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(33, 80, 0, 0);
        getContentPane().add(btnCurso2, gridBagConstraints);

        btnCurso3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnCurso3.setForeground(new java.awt.Color(153, 0, 51));
        btnCurso3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Libro3-64.png"))); // NOI18N
        btnCurso3.setText("Curso 3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(32, 80, 0, 0);
        getContentPane().add(btnCurso3, gridBagConstraints);

        btnCurso4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnCurso4.setForeground(new java.awt.Color(153, 0, 51));
        btnCurso4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/universidad64 - 2.png"))); // NOI18N
        btnCurso4.setText("Curso 4");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(33, 80, 49, 0);
        getContentPane().add(btnCurso4, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JButton getBtnCurso1() {
        return btnCurso1;
    }

    public JButton getBtnCurso2() {
        return btnCurso2;
    }

    public JButton getBtnCurso3() {
        return btnCurso3;
    }

    public JButton getBtnCurso4() {
        return btnCurso4;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCurso1;
    private javax.swing.JButton btnCurso2;
    private javax.swing.JButton btnCurso3;
    private javax.swing.JButton btnCurso4;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
