
package Vista;

import Modelo.GridLayoutEjemplo;

public class JDialogGridLayout extends javax.swing.JDialog {
    
    GridLayoutEjemplo grid = new GridLayoutEjemplo();

    public JDialogGridLayout(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGridLayout1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnGridLayout2 = new javax.swing.JButton();
        btnGridLayout3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnGridLayout1.setText("GridLayout1");
        btnGridLayout1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGridLayout1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Grid Layout");

        btnGridLayout2.setText("GridLayout2");
        btnGridLayout2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGridLayout2ActionPerformed(evt);
            }
        });

        btnGridLayout3.setText("GridLayout3");
        btnGridLayout3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGridLayout3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(btnGridLayout3)
                    .addComponent(btnGridLayout2)
                    .addComponent(btnGridLayout1))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addComponent(btnGridLayout1)
                .addGap(18, 18, 18)
                .addComponent(btnGridLayout2)
                .addGap(18, 18, 18)
                .addComponent(btnGridLayout3)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGridLayout1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGridLayout1ActionPerformed
        grid.GridLayout1();
        dispose();
    }//GEN-LAST:event_btnGridLayout1ActionPerformed

    private void btnGridLayout2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGridLayout2ActionPerformed
        grid.GridLayout2();
        dispose();
    }//GEN-LAST:event_btnGridLayout2ActionPerformed

    private void btnGridLayout3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGridLayout3ActionPerformed
        grid.GridLayout3();
        dispose();
    }//GEN-LAST:event_btnGridLayout3ActionPerformed

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGridLayout1;
    private javax.swing.JButton btnGridLayout2;
    private javax.swing.JButton btnGridLayout3;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
