package Vista;

public class VistaLayout extends javax.swing.JFrame {

    public VistaLayout() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnBorderLayout = new javax.swing.JButton();
        btnBoxLayout = new javax.swing.JButton();
        btnGridLayout = new javax.swing.JButton();
        btnFlowLayout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Layouts Managers");

        btnBorderLayout.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnBorderLayout.setForeground(new java.awt.Color(0, 51, 255));
        btnBorderLayout.setText("Border Layout");
        btnBorderLayout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorderLayoutActionPerformed(evt);
            }
        });

        btnBoxLayout.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnBoxLayout.setForeground(new java.awt.Color(0, 51, 255));
        btnBoxLayout.setText("Box Layout");
        btnBoxLayout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBoxLayoutActionPerformed(evt);
            }
        });

        btnGridLayout.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnGridLayout.setForeground(new java.awt.Color(0, 51, 255));
        btnGridLayout.setText("Grid Layout");
        btnGridLayout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGridLayoutActionPerformed(evt);
            }
        });

        btnFlowLayout.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnFlowLayout.setForeground(new java.awt.Color(0, 51, 255));
        btnFlowLayout.setText("Flow Layout");
        btnFlowLayout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFlowLayoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnFlowLayout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(btnGridLayout))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnBorderLayout)
                                .addGap(18, 18, 18)
                                .addComponent(btnBoxLayout)))
                        .addGap(57, 57, 57))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(94, 94, 94))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBorderLayout)
                    .addComponent(btnBoxLayout))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFlowLayout)
                    .addComponent(btnGridLayout))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBoxLayoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBoxLayoutActionPerformed
        JDialogBoxLayout box = new JDialogBoxLayout(this, true);
        box.setVisible(true);
    }//GEN-LAST:event_btnBoxLayoutActionPerformed

    private void btnBorderLayoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorderLayoutActionPerformed
        JDialogBorderLayout border = new JDialogBorderLayout(this, true);
        border.setVisible(true);
    }//GEN-LAST:event_btnBorderLayoutActionPerformed

    private void btnFlowLayoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFlowLayoutActionPerformed
        JDialogFlowLayout flow = new JDialogFlowLayout(this, true);
        flow.setVisible(true);
    }//GEN-LAST:event_btnFlowLayoutActionPerformed

    private void btnGridLayoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGridLayoutActionPerformed
        JDialogGridLayout grid = new JDialogGridLayout(this, true);
        grid.setVisible(true);
    }//GEN-LAST:event_btnGridLayoutActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorderLayout;
    private javax.swing.JButton btnBoxLayout;
    private javax.swing.JButton btnFlowLayout;
    private javax.swing.JButton btnGridLayout;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
