
package Vista;

import Modelo.FlowLayoutModelo;
import javax.swing.JButton;

public class JDialogFlowLayout extends javax.swing.JDialog {
    
    FlowLayoutModelo flow = new FlowLayoutModelo();

    public JDialogFlowLayout(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnFlowLayout2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnFlowLayout1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnFlowLayout2.setText("FlowLayout2");
        btnFlowLayout2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFlowLayout2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Flow Layout");

        btnFlowLayout1.setText("FlowLayout1");
        btnFlowLayout1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFlowLayout1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnFlowLayout2)
                    .addComponent(btnFlowLayout1)
                    .addComponent(jLabel1))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addComponent(btnFlowLayout1)
                .addGap(18, 18, 18)
                .addComponent(btnFlowLayout2)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFlowLayout2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFlowLayout2ActionPerformed
        /*flow.FlowLayout2();
        dispose();*/
    }//GEN-LAST:event_btnFlowLayout2ActionPerformed

    private void btnFlowLayout1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFlowLayout1ActionPerformed
      /*  flow.FlowLayout1();
        dispose();*/
    }//GEN-LAST:event_btnFlowLayout1ActionPerformed

    public JButton getBtnFlowLayout1() {
        return btnFlowLayout1;
    }

    public JButton getBtnFlowLayout2() {
        return btnFlowLayout2;
    }


    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFlowLayout1;
    private javax.swing.JButton btnFlowLayout2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
